# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Optimization Exploratorium
author: Siddharth Nand
only_build_toc_files: true
copyright: 2024, Siddharth Nand

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/sidnand/Optimization-Exploratorium  # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: true
  baseurl: "https://sidnand.github.io/Optimization Exploratorium"

search_engine:
  provider: lunr